from __future__ import annotations
from ._core import Environment, LeanObject, Runtime

__all__: list[str]

class Expr:
    @staticmethod
    def const_(name: str) -> Expr: ...
    @staticmethod
    def bvar(idx: int) -> Expr: ...
    @staticmethod
    def sort(level: int) -> Expr: ...
    def app(self, arg: Expr) -> Expr: ...
    @staticmethod
    def lam(name: str, ty: Expr, body: Expr) -> Expr: ...
    @staticmethod
    def forall_(name: str, ty: Expr, body: Expr) -> Expr: ...
    @staticmethod
    def arrow(from_: Expr, to: Expr) -> Expr: ...
    @staticmethod
    def eq(ty: Expr, lhs: Expr, rhs: Expr) -> Expr: ...
    @staticmethod
    def eq_refl(ty: Expr, val: Expr) -> Expr: ...
    @staticmethod
    def nat_lit(n: int) -> Expr: ...
    @staticmethod
    def str_lit(s: str) -> Expr: ...

class TacticState:
    def __init__(self) -> None: ...
    @property
    def num_goals(self) -> int: ...
    @property
    def is_solved(self) -> bool: ...
    @property
    def goals_pp(self) -> list[str]: ...
    def intro(self, name: str) -> TacticResult: ...
    def exact(self, expr: Expr) -> TacticResult: ...
    def rfl(self) -> TacticResult: ...
    def apply_expr(self, expr: Expr) -> TacticResult: ...
    def focus(self) -> TacticState: ...
    def swap(self) -> TacticState: ...

class TacticResult:
    success: bool
    error: str | None
    next_state: TacticState | None
    def __bool__(self) -> bool: ...

class MetaContext:
    def __init__(self, env: LeanObject) -> None: ...
    def mk_goal(self, goal_type: Expr) -> TacticState: ...
    @property
    def is_valid(self) -> bool: ...

class ProofEnvironment:
    def __init__(self, env: LeanObject, theorem_name: str) -> None: ...
    def reset(self) -> TacticState: ...
    def step(self, state: TacticState, tactic: str) -> tuple[TacticState, float, bool, dict]: ...

class BatchVerifier:
    def __init__(self, num_workers: int = 8) -> None: ...
    def verify_batch(self, states: list[TacticState], tactics: list[str]) -> list[TacticResult]: ...
    @property
    def workers(self) -> int: ...
