class Runtime:
    def __init__(self) -> None: ...
    @property
    def is_initialized(self) -> bool: ...

class LeanObject:
    @property
    def type_name(self) -> str: ...
    def is_scalar(self) -> bool: ...

class Environment: ...

class MetaContext:
    def __init__(self, env: LeanObject) -> None: ...
    def run(self, computation: LeanObject) -> LeanObject: ...
    @property
    def is_valid(self) -> bool: ...
